service: aws-postgres-serverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:

  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: /hello
  
  getDistricts:
    handler: handler.getDistricts
    events:
      - http:
          method: get
          path: /getDistricts
  
  getDistrictsForState:
    handler: handler.getDistrictsForState
    events:
      - http:
          method: get
          path: /districtsForState/{state_abbrev}

plugins:
  - serverless-offline